# Site's title
title: Selene Archive

# Disable automatic theming
theme: null

collections:
  topics:
    output: true
    permalink: /:collection/:name

# Additional subdirectories to include
defaults:
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default
